### Sign Up
POST http://localhost:5050/api/auth/signup
Content-Type: application/json

{
  "username": "john_doe",
  "email": "john.doe@example.com",
  "password": "Password123",
  "name": "John Doe"
}

### Login
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "email": "john.doe@example.com",
  "password": "Password123"
}

### Logout
POST http://localhost:3000/api/auth/logout
Authorization: Bearer {{accessToken}}
Content-Type: application/json

### Refresh Token
POST http://localhost:3000/api/auth/refresh-token
Content-Type: application/json
